### ISSUE TITLE
inline-flex support

### ISSUE THREAD

**Issue by abdullahtariq1171** [realadvisor/react-system#13]
add support for `inline-flex`

**Comment by TrySound** [comment]
Hi, inline elements does not make much sense in most layouts. If you want to get inline-flex add css prop.

```js
<Flex css={{ display: 'inline-flex' }}>
</Flex>
```

**Comment by abdullahtariq1171** [comment]
hey, Thanks for responding. I've not used `css` prop at all, at least till this point, so was looking for something `inlineFlex` boolean prop. But I see this works. Thank you for creating this awesome package  🎉
